// <auto-generated />
namespace Swas.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WasteType_Coeficinet_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WasteType_Coeficinet_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201605011929114_WasteType_Coeficinet_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
