// <auto-generated />
namespace Swas.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Add_Session_ActivityDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Add_Session_ActivityDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201606042059139_User_Add_Session_ActivityDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
