// <auto-generated />
namespace Swas.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Permission_Role_RollePermision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Permission_Role_RollePermision));
        
        string IMigrationMetadata.Id
        {
            get { return "201605291110495_Permission_Role_RollePermision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
