// <auto-generated />
namespace Swas.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_UserDetail_UserRegion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_UserDetail_UserRegion));
        
        string IMigrationMetadata.Id
        {
            get { return "201605302228491_User_UserDetail_UserRegion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
