// <auto-generated />
namespace Swas.Data.Access.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agreement_Add_Start_AND_DATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agreement_Add_Start_AND_DATE));
        
        string IMigrationMetadata.Id
        {
            get { return "201605261935436_Agreement_Add_Start_AND_DATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
